### ISSUE TITLE
Server crasehd with java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by lays24mc** [ezterry/DefaultWorldGenerator-port#10]
Hi,

i reinstall my server, because i had a corupted minecraft.jar. Than i install my old world and start my server, but he start with a crashloop. I use the Modpack ATM3 1.12.2. With an new world work all fine.

Here my crashlog:
https://pastebin.com/CmAp7t1z

can you help me? What is wrong?

**Comment by ezterry** [comment]
In your world directory (or world's data directory) the file state.defaultworldgenerator-port.data is curupted.. I don't think the pack in question uses features that will be harmed if you delete this file and let it rest generate (backup first) however this might be an indicator of other files having not been saved correctly.

If auto backup was enabled you may wish to see if going to one of the zipped backups is more stable.
