### ISSUE TITLE
[Request] Any chance of getting this mod updated to 1.14 forge?

### ISSUE THREAD

**Issue by Electrofried** [ezterry/DefaultWorldGenerator-port#13]
This is a fantastic mod for pack makers and allows for some great configuration, it would be fantastic if you could look at porting it over to 1.14.4 forge

**Comment by ezterry** [comment]
Given the changes in minecraft and forge.. this is not a simple update, but rather a re-write.  A bit unfortunate since I just made a large re-factor for 1.12,

That said I've started the process, so keep a lookout
