### ISSUE TITLE
Some user playing All the mods remix reported this. have no clue what caused it

### ISSUE THREAD

**Issue by furtabs** [ezterry/DefaultWorldGenerator-port#14]
https://pastebin.com/xVVCYpRV

**Comment by ezterry** [comment]
Hi,

This is likely a corrupted world save.
Specifically the data in state.defaultworldgenerator-port.data was unable to be read  (Well it could be read but had bad data in it)

While I can't say if anything else may be bad in the world save (this file is only written on world start)

Things to attempt:

1) Restore to a recent backup
2) if the recent backup is too old, restore state.defaultworldgenerator-port.data from the lattest backup, in the current save
3) In many cases simply deleting the state.defaultworldgenerator-port.data will cause it to regenerate correctly, note if you have multiple default world types the world will forget which one it is and follow the first for any advanced default-world gen features (copying of data files, or commands run)
4) If 3 causes issues, manually create a world with the same default world type as the error prone world, and copy the state.defaultworldgenerator-port.data from there.

While this is many steps, it mostly just is either try a backup or delete the state.defaultworldgenerator-port.data file from most users

**Comment by ezterry** [comment]
Just to add assuming you mean this:
https://github.com/AllTheMods/ATM-3/blob/master/overrides/config/defaultworldgenerator-port/worldsettings.data

Deleting the state.defaultworldgenerator-port.data in the world save will be safe I see none of the advanced config in use
