### ISSUE TITLE
World generation does not change on servers

### ISSUE THREAD

**Issue by noamsm** [ezterry/DefaultWorldGenerator-port#2]
I am making a modpack using this mod, I want to make a server pack for other users to download but the mod doesn't seem to be working on servers.

Is there a fix for that?

This is my config:
-----------------------------------------------------------------------------------------------------------
# Configuration file

general {
    # The world customization string (JSON, or super flat string) [default: ]
    S:CustomizationJson={"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":0.0,"seaLevel":1,"useCaves":false,"useDungeons":false,"dungeonChance":1,"useStrongholds":false,"useVillages":false,"useMineShafts":false,"useTemples":false,"useMonuments":false,"useRavines":false,"useWaterLakes":false,"waterLakeChance":1,"useLavaLakes":false,"lavaLakeChance":10,"useLavaOceans":false,"fixedBiome":12,"biomeSize":8,"riverSize":1,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":9,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":9,"goldCount":2,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":8,"diamondCount":1,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":16,"lapisSpread":16}

    # Prevent the user from changing the world type. [default: false]
    B:"Lock Worldtype"=true

    # The Suggested Seed for the pack, leave blank for a random seed, notethe player can change this even if locked [default: ]
    S:Seed=

    # Enabling this will display all world generators installed, useful for debug [default: false]
    B:"Show World Generators in Log"=false

    # The world generator to select by default [default: default]
    S:"World Generator"=customized
}

-----------------------------------------------------------------------------------------------------------

Thanks, Blue_future

**Comment by ezterry** [comment]
The world type and customization strings for a new word are save in "server.properties" file on the server

Default world generator will never override the values in this file, as this would prevent a server operator from customizing their server.

However if the user doesn't have a server.properties (or the world generation lines are missing) it will default them to the information defined in the config.

The values updated by default world generator include:
* level type
* generator-settings
* level-seed

To test ensure you delete the server.properties file (as well as any already generated world) and start the server again.

If you are using an existing server.properties file for other settings, i recommend only including the lines you need, allowing the others to be re-generated from the defaults.  For this mod in particular you will want to delete the line for the 3 mentioned fields unless you are overriding them deliberately.  Then if the server creates a new world it will use the correct settings.

**Comment by ezterry** [comment]
If there are any questions or problems after taking in consideration the above please let me know, for now I believe this issue can be marked closed.
