### ISSUE TITLE
[Suggestion] Sets of default world generators/Generate structures

### ISSUE THREAD

**Issue by heidrifx** [ezterry/DefaultWorldGenerator-port#3]
So my idea is wether you could add a feature to only enable certain generators (like default and quark_realistic) but nothing else. Would be pretty amazing because lately there are so many different kinds of generators, so only enabling a few would be cool.
Another request of mine would be if you could consider adding an option to set the Generate structures option to a fix value by default and maybe even add an option to lock the button in the menu.

**Comment by ezterry** [comment]
Sorry for the delay on reply, (starting a new job and have been a bit busy) but regarding your requests:

* Regarding Generate structures, presumably I could add a toggle on generate structures like I did bonus chests.

* Regarding the shortened list, I feel its not a good design to reduce the list in the advanced options screen.  (either lock it, or have it preset to the option you want, but let your users change it)  This means if I was to implement something like this I'd want it earlier in the user flow (and separate from the lock), such as appearing on the main new game screen (or maybe even before you can enter the world name).  I've thought about this before, and my conclusions then was most cases the mod "Lockdown" will better suit most packs with such requirements, however I will think about it some more and maybe in the future it will be added in.

**Comment by ezterry** [comment]
Generate structures toggle (enable,disable,force,block) is part of the DWG2.0 for 1.12 interface.

Also 1.12 now supports multiple defaults, each can be locked or allow customization per the pack designer.  Thus this enhancement is implemented! at least once your packs make it to 1.12.
