### ISSUE TITLE
The current configuration options don't seem to allow adding biomes from B.O.P

### ISSUE THREAD

**Issue by Winddbourne** [ezterry/DefaultWorldGenerator-port#6]
Normally you can add biome of plenty world biomes to standard generation when you make a custom world. Due to this they removed those options from their own configuration files.

However there doesn't seem to be a way to either manually alter the custom world text string, or to manually add world generators for the mod to pull biomes out of. Or for that matter once RTG updates to allow us to use those great gigantic trees but that is a different issue. lol

Hopefully I'm just missing something and the text portion of the settings are actually easily accessible, or I missed some option but in case it's not there I'd like to get that fixed for the future. :)

**Comment by ezterry** [comment]
Default world generator no longer permits manually editing the basic world configuration outside of the mc client.

The configuration string thus must be configured as you would normally using world types configuration GUI as you would for single player. (For the customized/super flat world types this is the vanilla GUI, and you can set the string in the presets subscreen, for a modded world you will need to ask the mod author how additional customizations are to be done if even supported.  If the configuration button is inactive your current world type has no configuration options.

If your world type is not listed the mod did not properly register it prior to you entering the mod config screen.

Some of what you are describing I'm not sure ever related to default world generator.. maybe I'm not fully clear on what you are trying to do or not seeing that you expect.

**Comment by Winddbourne** [comment]
This link may help explain what I am trying to do:

http://biomesoplenty.wikia.com/wiki/Configuration

**Comment by ezterry** [comment]
Choose biomes o plenty, then press configure, and use the biomes o plenty GUI to customize the world, if there are options unavailable please open an issue with BOP. To allow access if there is not currently a way.

**Comment by ezterry** [comment]
Note this is the same GUI a single player new world provides when the normal customize button is pressed.
